// Lista de bairros, loteamentos e condomínios de Itatiba (SP).
// Fontes: base local + índice postal MBI (~166 localidades) + OpenStreetMap.
// Entradas sem lat/lng ainda entram na busca; o geocoder tenta resolver na hora.
window.ITATIBA_LOCAIS = [
  { nome: "Alpes do Cruzeiro", tipo: "bairro" },
  { nome: "Bairro da Aparecidinha", tipo: "bairro", aliases: ["da Aparecidinha"] },
  { nome: "Bairro da Ponte", tipo: "bairro", aliases: ["da Ponte"], lat: -22.978733, lng: -46.832142 },
  { nome: "Bairro da Posse", tipo: "bairro", aliases: ["da Posse"] },
  { nome: "Bairro das Brotas", tipo: "bairro", aliases: ["das Brotas"] },
  { nome: "Bairro do Engenho", tipo: "bairro", aliases: ["Engenho","do Engenho","Engenho Itatiba"], address: "Rua José de Oliveira — Bairro do Engenho", lat: -23.0213768, lng: -46.846043 },
  { nome: "Bairro do Morro", tipo: "bairro", aliases: ["do Morro"] },
  { nome: "Bairro do Pinhal", tipo: "bairro", aliases: ["do Pinhal"], lat: -23.063189, lng: -46.837884 },
  { nome: "Bairro dos Baldos", tipo: "bairro", aliases: ["dos Baldos"], lat: -22.9679908, lng: -46.9109734 },
  { nome: "Bairro dos Leites", tipo: "bairro", aliases: ["dos Leites"] },
  { nome: "Bairro dos Machados", tipo: "bairro", aliases: ["dos Machados"] },
  { nome: "Bairro dos Pintos", tipo: "bairro", aliases: ["dos Pintos"], lat: -23.017142, lng: -46.771966 },
  { nome: "Bairro dos Pires", tipo: "bairro", aliases: ["dos Pires"] },
  { nome: "Bairro Itapema", tipo: "bairro", aliases: ["Itapema"], lat: -23.042247, lng: -46.872671 },
  { nome: "Bairro Morro Azul", tipo: "bairro", aliases: ["Morro Azul"], lat: -23.065798, lng: -46.767113 },
  { nome: "Bairro Pedras de Ouro", tipo: "bairro", aliases: ["Pedras de Ouro"] },
  { nome: "Bairro Tapera Grande", tipo: "bairro", aliases: ["Tapera Grande"], lat: -23.0483583, lng: -46.8775538 },
  { nome: "Barreiro", tipo: "bairro", lat: -22.9407003, lng: -46.7240452 },
  { nome: "Bela Vista", tipo: "bairro" },
  { nome: "Cachoeiras do Imaratá", tipo: "bairro" },
  { nome: "Capela do Barreiro", tipo: "bairro", lat: -22.9407003, lng: -46.7240452 },
  { nome: "Centro", tipo: "bairro", lat: -23.0056, lng: -46.8389 },
  { nome: "Centro Empresarial Roque Faccina", tipo: "bairro" },
  { nome: "Chácara San Martin I", tipo: "bairro" },
  { nome: "Chácara San Martin II", tipo: "bairro" },
  { nome: "Chácara Santa Cruz dos Pires", tipo: "bairro", lat: -22.968446, lng: -46.732407 },
  { nome: "Chácaras Bredariol", tipo: "bairro" },
  { nome: "Cidade Jardim", tipo: "bairro", aliases: ["Bairro Cidade Jardim"], lat: -23.0128476, lng: -46.8274108 },
  { nome: "Clube de Campo Fazenda", tipo: "bairro", aliases: ["Clube de Campo"], lat: -22.97635, lng: -46.926341 },
  { nome: "Cocais", tipo: "bairro", aliases: ["Bairro Cocais"], lat: -23.004366, lng: -46.891881 },
  { nome: "Distrito Industrial Alfredo Relo", tipo: "bairro" },
  { nome: "Encosta do Sol", tipo: "bairro" },
  { nome: "Fazenda Malabar", tipo: "bairro" },
  { nome: "Jardim Alto de Santa Cruz", tipo: "bairro", aliases: ["Jardim Alto da Santa Cruz","Alto da Santa Cruz","Alto de Santa Cruz"], lat: -22.9932241, lng: -46.8340824 },
  { nome: "Jardim América", tipo: "bairro", lat: -23.004212, lng: -46.828066 },
  { nome: "Jardim Ana Maria", tipo: "bairro" },
  { nome: "Jardim Arizona", tipo: "bairro", lat: -23.0199526, lng: -46.8378857 },
  { nome: "Jardim Belém", tipo: "bairro", lat: -23.0177202, lng: -46.8389947 },
  { nome: "Jardim Belvedere", tipo: "bairro" },
  { nome: "Jardim Carlos Borella", tipo: "bairro", lat: -23.004172, lng: -46.829813 },
  { nome: "Jardim Coronel", tipo: "bairro" },
  { nome: "Jardim Coronel Peroba", tipo: "bairro", lat: -23.010607, lng: -46.850283 },
  { nome: "Jardim Cremonese", tipo: "bairro", aliases: ["Jardim Cremonesi","Cremonese"], lat: -23.021054, lng: -46.843722 },
  { nome: "Jardim da Luz", tipo: "bairro", lat: -23.0214011, lng: -46.8428028 },
  { nome: "Jardim das Laranjeiras", tipo: "bairro" },
  { nome: "Jardim das Nações", tipo: "bairro", lat: -23.0071656, lng: -46.8673999 },
  { nome: "Jardim de Lucca", tipo: "bairro", aliases: ["Jardim de Luca"], lat: -23.0117724, lng: -46.8428958 },
  { nome: "Jardim Delforno", tipo: "bairro" },
  { nome: "Jardim do Leste", tipo: "bairro" },
  { nome: "Jardim dos Lagos", tipo: "bairro" },
  { nome: "Jardim Esplanada", tipo: "bairro" },
  { nome: "Jardim Ester", tipo: "bairro", lat: -23.014813, lng: -46.837109 },
  { nome: "Jardim Galetto", tipo: "bairro", lat: -23.0107836, lng: -46.8228636 },
  { nome: "Jardim Harmonia", tipo: "bairro" },
  { nome: "Jardim Ipê", tipo: "bairro", lat: -23.008493, lng: -46.851747 },
  { nome: "Jardim Leonor", tipo: "bairro", lat: -22.9657428, lng: -46.8182441 },
  { nome: "Jardim Lúcia", tipo: "bairro" },
  { nome: "Jardim Maria", tipo: "bairro", lat: -22.993529, lng: -46.835083 },
  { nome: "Jardim Mateus", tipo: "bairro", lat: -23.0083593, lng: -46.8356228 },
  { nome: "Jardim México", tipo: "bairro", lat: -23.000632, lng: -46.820259 },
  { nome: "Jardim Monte Verde", tipo: "bairro" },
  { nome: "Jardim Morumbi", tipo: "bairro" },
  { nome: "Jardim Nardin", tipo: "bairro" },
  { nome: "Jardim Nice", tipo: "bairro", lat: -22.999282, lng: -46.839154 },
  { nome: "Jardim Nossa Senhora das Graças", tipo: "bairro", lat: -22.989935, lng: -46.849573 },
  { nome: "Jardim Nossa Senhora de Fátima", tipo: "bairro", aliases: ["Nossa Senhora de Fátima","Nossa Senhora de Fatima","Bairro Nossa Senhora de Fátima","Bairro Nossa Senhora de Fatima","Jardim Nossa Senhora de Fatima"], address: "Rua João Corradini — Jardim Nossa Senhora de Fátima", lat: -23.0096313, lng: -46.8465374 },
  { nome: "Jardim Nova América", tipo: "bairro" },
  { nome: "Jardim Nova Esperança", tipo: "bairro", lat: -22.9660936, lng: -46.9135595 },
  { nome: "Jardim Nova Itatiba", tipo: "bairro", lat: -22.9660936, lng: -46.9135595 },
  { nome: "Jardim Novo Horizonte", tipo: "bairro" },
  { nome: "Jardim Palladino", tipo: "bairro", lat: -22.997012, lng: -46.850606 },
  { nome: "Jardim Salessi", tipo: "bairro", lat: -22.997554, lng: -46.846532 },
  { nome: "Jardim Santa Cruz", tipo: "bairro" },
  { nome: "Jardim Santa Filomena", tipo: "bairro", lat: -23.007525, lng: -46.854914 },
  { nome: "Jardim Santa Luzia", tipo: "bairro", aliases: ["Jd Santa Luzia"], address: "Rua José Solito — Jardim Santa Luzia", lat: -23.0133217, lng: -46.8441374 },
  { nome: "Jardim Santa Rosa", tipo: "bairro", lat: -23.0262918, lng: -46.8413125 },
  { nome: "Jardim Santo Antônio", tipo: "bairro", lat: -23.004773, lng: -46.831291 },
  { nome: "Jardim São João", tipo: "bairro" },
  { nome: "Jardim São José", tipo: "bairro", lat: -23.0077372, lng: -46.8373019 },
  { nome: "Jardim São Luiz", tipo: "bairro" },
  { nome: "Jardim São Luiz II", tipo: "bairro", lat: -23.013111, lng: -46.829552 },
  { nome: "Jardim São Marcos", tipo: "bairro" },
  { nome: "Jardim Stela", tipo: "bairro", aliases: ["Jardim Stella","Stela","Stella"], address: "Travessa Tereza Parizotto Roson — Jardim Stela", lat: -23.017702, lng: -46.8387301 },
  { nome: "Jardim Tereza", tipo: "bairro", lat: -23.0109234, lng: -46.8332047 },
  { nome: "Jardim Verona", tipo: "bairro", lat: -23.003541, lng: -46.818319 },
  { nome: "Jardim Virgínia", tipo: "bairro", lat: -22.98618, lng: -46.849197 },
  { nome: "Loteamento Aída Haddad Jafet", tipo: "bairro", lat: -23.012479, lng: -46.8646634 },
  { nome: "Loteamento Caminhos do Sol", tipo: "bairro", lat: -22.964482, lng: -46.893615 },
  { nome: "Loteamento Fernando Momentel", tipo: "bairro" },
  { nome: "Loteamento Itatiba Country Club", tipo: "bairro" },
  { nome: "Loteamento Itatiba Park", tipo: "bairro", lat: -23.0301784, lng: -46.8513301 },
  { nome: "Loteamento Morrão da Força", tipo: "bairro", aliases: ["Morrão da Força","Morrao da Forca"], address: "Rua José Milton Pizzi — Loteamento Morrão da Força" },
  { nome: "Loteamento Padovani", tipo: "bairro", lat: -23.018399, lng: -46.809516 },
  { nome: "Loteamento Parque da Colina II", tipo: "bairro", aliases: ["Parque da Colina II"], lat: -23.0131598, lng: -46.8240803 },
  { nome: "Loteamento Parque Empresarial Adelelmo Corradini", tipo: "bairro", aliases: ["Parque Empresarial Adelelmo Corradini"] },
  { nome: "Loteamento Rei de Ouro", tipo: "bairro" },
  { nome: "Loteamento Residencial Central Park I", tipo: "bairro", lat: -23.0131598, lng: -46.8240803 },
  { nome: "Loteamento Residencial Central Park II", tipo: "bairro", aliases: ["Central Park II"], lat: -23.0131598, lng: -46.8240803 },
  { nome: "Loteamento Residencial Terra Nova", tipo: "bairro" },
  { nome: "Loteamento Residencial Vale das Águas", tipo: "bairro", aliases: ["Vale das Águas"] },
  { nome: "Loteamento Santo Antônio", tipo: "bairro", lat: -22.99672, lng: -46.817457 },
  { nome: "Loteamento Vila Real", tipo: "bairro", aliases: ["Vila Real"], lat: -22.98308, lng: -46.846489 },
  { nome: "Mato Dentro", tipo: "bairro" },
  { nome: "Mombuca", tipo: "bairro", aliases: ["Bairro Mombuca"], lat: -23.027704, lng: -46.89114 },
  { nome: "Morada das Fontes", tipo: "bairro" },
  { nome: "Morada dos Pássaros", tipo: "bairro", lat: -23.0184942, lng: -46.8306083 },
  { nome: "Nova Itatiba", tipo: "bairro", aliases: ["Bairro Nova Itatiba"], lat: -23.0978173, lng: -46.8412392 },
  { nome: "Novo Cruzeiro", tipo: "bairro", aliases: ["Bairro Novo Cruzeiro","Novo Cuzeiro","Bairro Novo Cuzeiro"], address: "Rua Nagib Curi — Novo Cruzeiro", lat: -22.99726, lng: -46.85465 },
  { nome: "Núcleo Habitacional Pedro Costa", tipo: "bairro" },
  { nome: "Núcleo Habitacional Prefeito Erasmo Chrispim", tipo: "bairro" },
  { nome: "Núcleo Habitacional Roberto Panzarin", tipo: "bairro" },
  { nome: "Núcleo Residencial Abramo Delforno", tipo: "bairro" },
  { nome: "Núcleo Residencial Afonso Zupardo", tipo: "bairro" },
  { nome: "Núcleo Residencial Doutor Luiz de Mattos Pimenta", tipo: "bairro", lat: -23.021734, lng: -46.8501954 },
  { nome: "Núcleo Residencial João Corradini", tipo: "bairro", lat: -22.989746, lng: -46.828568 },
  { nome: "Núcleo Residencial Pedro Fumachi", tipo: "bairro", lat: -23.00216, lng: -46.810606 },
  { nome: "Núcleo Residencial Porto Seguro", tipo: "bairro", lat: -23.0289186, lng: -46.8529801 },
  { nome: "Núcleo Residencial Vale Verde", tipo: "bairro" },
  { nome: "Paraíso das Aves", tipo: "bairro" },
  { nome: "Parque da Colina", tipo: "bairro", aliases: ["Parque da Colina I"], lat: -23.0140447, lng: -46.8173854 },
  { nome: "Parque da Fazenda", tipo: "bairro", lat: -23.033701, lng: -46.8410556 },
  { nome: "Parque das Laranjeiras", tipo: "bairro", lat: -23.015421, lng: -46.818138 },
  { nome: "Parque Ferraz Costa", tipo: "bairro", lat: -22.9995115, lng: -46.8335248 },
  { nome: "Parque Industrial San Francisco", tipo: "bairro" },
  { nome: "Parque Luís Latorre", tipo: "bairro", aliases: ["Parque Luis Latorre"], lat: -23.0316212, lng: -46.8391448 },
  { nome: "Parque Nova Xampirra", tipo: "bairro" },
  { nome: "Parque São Francisco", tipo: "bairro", lat: -23.0027, lng: -46.8142 },
  { nome: "Parque São Gabriel", tipo: "bairro" },
  { nome: "Parque São Vicente", tipo: "bairro", lat: -23.011092, lng: -46.832299 },
  { nome: "Parque Tescarollo", tipo: "bairro", lat: -23.006906, lng: -46.826231 },
  { nome: "Pomar São Jorge", tipo: "bairro" },
  { nome: "Ponte Nova", tipo: "bairro", aliases: ["Bairro Ponte Nova"], lat: -23.007731, lng: -46.793712 },
  { nome: "Portal da Colina", tipo: "bairro" },
  { nome: "Princesa da Colina", tipo: "bairro" },
  { nome: "Real Parque Dom Pedro I", tipo: "bairro" },
  { nome: "Recanto Beira Rio", tipo: "bairro" },
  { nome: "Recanto da Paz", tipo: "bairro", aliases: ["Bairro Recanto da Paz"] },
  { nome: "Recanto das Estrelas", tipo: "bairro" },
  { nome: "Recanto das Laranjeiras", tipo: "bairro" },
  { nome: "Recanto do Parque", tipo: "bairro", aliases: ["Bairro Recanto do Parque"], lat: -22.999031, lng: -46.826557 },
  { nome: "Recanto dos Pássaros", tipo: "bairro" },
  { nome: "Recanto Princesa da Colina", tipo: "bairro" },
  { nome: "Recreio Costa Verde", tipo: "bairro" },
  { nome: "Residencial Fazenda Serrinha", tipo: "bairro", lat: -23.0179425, lng: -46.8254953 },
  { nome: "Residencial Flamboyant", tipo: "bairro" },
  { nome: "Residencial Grêmio", tipo: "bairro" },
  { nome: "Residencial Moenda", tipo: "bairro", lat: -22.95417, lng: -46.763563 },
  { nome: "Santa Cruz", tipo: "bairro", lat: -22.997394, lng: -46.8351906 },
  { nome: "Sítio da Moenda", tipo: "bairro", aliases: ["Bairro Sítio da Moenda"], lat: -22.95417, lng: -46.763563 },
  { nome: "Summertime Barreiro", tipo: "bairro" },
  { nome: "Terras de São Sebastião", tipo: "bairro", aliases: ["Bairro Terras de São Sebastião"], lat: -22.950151, lng: -46.771397 },
  { nome: "Terras de Savion", tipo: "bairro" },
  { nome: "Vila Bela Vista", tipo: "bairro", lat: -23.011271, lng: -46.843869 },
  { nome: "Vila Belém", tipo: "bairro", aliases: ["Vila Belem"], lat: -23.0078439, lng: -46.8469096 },
  { nome: "Vila Brasileira", tipo: "bairro", lat: -23.0052691, lng: -46.8488421 },
  { nome: "Vila Capelletto", tipo: "bairro", aliases: ["Vila Capeletto","Capeletto","Capelletto"], lat: -22.997881, lng: -46.844189 },
  { nome: "Vila Cassaro", tipo: "bairro", lat: -23.006917, lng: -46.847966 },
  { nome: "Vila Centenário", tipo: "bairro", lat: -23.004663, lng: -46.825238 },
  { nome: "Vila Cremonesi", tipo: "bairro", aliases: ["Jardim Cremonese","Jardim Cremonesi","Cremonese","Cremonesi"], lat: -23.021054, lng: -46.843722 },
  { nome: "Vila Cristo Redentor", tipo: "bairro", lat: -22.998815, lng: -46.84043 },
  { nome: "Vila Cruzeiro", tipo: "bairro", aliases: ["Cruzeiro","Cuzeiro","Bairro Cruzeiro","Bairro Cuzeiro","Praça Cruzeiro"], address: "Praça Cruzeiro — Vila Cruzeiro", lat: -23.0039859, lng: -46.8467996 },
  { nome: "Vila Fassina", tipo: "bairro", lat: -23.001143, lng: -46.839329 },
  { nome: "Vila Mutton", tipo: "bairro", lat: -23.0019522, lng: -46.8353315 },
  { nome: "Vila Pabreu", tipo: "bairro", aliases: ["Villa Pabreu","Pabreu"], address: "Alameda Senador Paulo Abreu — Vila Pabreu", lat: -23.0038692, lng: -46.8449141 },
  { nome: "Vila Penteado", tipo: "bairro" },
  { nome: "Vila Prudente de Moraes", tipo: "bairro", lat: -23.00188, lng: -46.838802 },
  { nome: "Vila Rita", tipo: "bairro", lat: -23.00783, lng: -46.82568 },
  { nome: "Vila Salessi", tipo: "bairro", lat: -22.997554, lng: -46.846532 },
  { nome: "Vila Santa Clara", tipo: "bairro", lat: -23.010556, lng: -46.843969 },
  { nome: "Vila Santa Cruz", tipo: "bairro", lat: -22.998772, lng: -46.836123 },
  { nome: "Vila Santa Luzia", tipo: "bairro", lat: -23.012325, lng: -46.8457549 },
  { nome: "Vila Santa Terezinha", tipo: "bairro", lat: -23.0079944, lng: -46.829861 },
  { nome: "Vila São Caetano", tipo: "bairro" },
  { nome: "Vila Tescarollo", tipo: "bairro", aliases: ["Vila Tescarolo"], lat: -23.006906, lng: -46.826231 },
  { nome: "Village de Piemonte", tipo: "bairro" },
  { nome: "Village do Sol", tipo: "bairro" },
  { nome: "Vivendas do Engenho D'Água", tipo: "bairro", aliases: ["Bairro Vivendas do Engenho D'Água"], lat: -22.958748, lng: -46.784565 },
  { nome: "Arts", tipo: "condominio", aliases: ["Condomínio Arts","GSP Arts"] },
  { nome: "Beija-Flor", tipo: "condominio", aliases: ["Condomínio Residencial Beija-Flor","Residencial Beija Flor","Cond. Beija Flor"], lat: -23.0163221, lng: -46.8290591 },
  { nome: "Bella Morada", tipo: "condominio", aliases: ["Residencial Bella Morada"] },
  { nome: "Bosque dos Pires", tipo: "condominio", aliases: ["Condomínio Bosque dos Pires","Residencial Bosque dos Pires"], lat: -22.977169, lng: -46.728817 },
  { nome: "Botanique", tipo: "condominio", aliases: ["Condomínio Botanique Itatiba"] },
  { nome: "Central Park", tipo: "condominio", aliases: ["Central Park I","Central Park II"], lat: -23.0131598, lng: -46.8240803 },
  { nome: "Dolce Vita", tipo: "condominio", aliases: ["Loteamento Residencial Dolce Vita"] },
  { nome: "Ecologie Residencial", tipo: "condominio", aliases: ["Ecologie Residencial Itatiba","Ecologie"] },
  { nome: "Exclusivitat", tipo: "condominio" },
  { nome: "Fazenda Dona Carolina", tipo: "condominio", aliases: ["Loteamento Fazenda Dona Carolina","Dona Carolina"], lat: -22.939588, lng: -46.7010142 },
  { nome: "Giardino D' Itália", tipo: "condominio", aliases: ["Bairro Giardino D' Itália","Giardino D'Italia","Giardino D Italia"], lat: -23.020285, lng: -46.853867 },
  { nome: "Green Ville", tipo: "condominio", aliases: ["Residencial Green Ville"] },
  { nome: "Itaembú", tipo: "condominio", aliases: ["Condomínio Itaembu","Itaembu"] },
  { nome: "Itatiba Country Club", tipo: "condominio", aliases: ["Condomínio Itatiba Country Club","Country Club"], lat: -23.0221311, lng: -46.8147891 },
  { nome: "Jardim Botânico", tipo: "condominio", aliases: ["Loteamento Residencial Jardim Botânico"] },
  { nome: "Jardim das Paineiras", tipo: "condominio", aliases: ["Jardim Paineiras","Paineiras","Condomínio Jardim das Paineiras","Condomínio Paineiras","Loteamento Jardim das Paineiras","Residencial Jardim das Paineiras"], address: "Avenida Guido Monte — Loteamento Jardim das Paineiras", lat: -22.932409, lng: -46.81497 },
  { nome: "Novo Engenho Place", tipo: "condominio", aliases: ["Condomínio Novo Engenho Place","Engenho Place"] },
  { nome: "Portal de Itá", tipo: "condominio", aliases: ["Portal de Ita"], lat: -23.0174075, lng: -46.8309685 },
  { nome: "Portal San Giovanni", tipo: "condominio", aliases: ["Portal San Giovani","San Giovanni"] },
  { nome: "Privilege", tipo: "condominio", aliases: ["Condomínio Privilege","Condominio Privilege","Privilege Residencial","Privilege Residencial Clube","Residencial Privilege","Residencial Privilége","Privilége","Privilége Residencial Clube","Privilege Itatiba"], address: "Rua Santo Antônio, 1750 — Jardim México, 13253-400", lat: -22.9991045, lng: -46.8174569 },
  { nome: "Quinta da Primavera", tipo: "condominio" },
  { nome: "Reserva Bellano", tipo: "condominio", aliases: ["Residencial Reserva Bellano"] },
  { nome: "Reserva da Mata", tipo: "condominio", aliases: ["Condomínio Residencial Reserva da Mata"] },
  { nome: "Reserva Santa Rosa", tipo: "condominio", aliases: ["Condomínio Reserva Santa Rosa","Reserva de Santa Rosa","Residencial Fazenda Santa Rosa"] },
  { nome: "Residencial Tescarollo", tipo: "condominio" },
  { nome: "San Diego", tipo: "condominio" },
  { nome: "San Paolo Residencial", tipo: "condominio", aliases: ["San Paolo"], lat: -23.0153039, lng: -46.8306789 },
  { nome: "Savoia Palace", tipo: "condominio", aliases: ["Savoia Palace Itatiba"] },
  { nome: "Sete Lagos", tipo: "condominio", aliases: ["Condomínio 7 Lagos","7 Lagos"] },
  { nome: "Sonhare", tipo: "condominio" },
  { nome: "Terras da Fazenda", tipo: "condominio", aliases: ["Loteamento Terras da Fazenda"] },
  { nome: "Terras de San Marco", tipo: "condominio", aliases: ["San Marco"] },
  { nome: "Terras de Santa Cruz", tipo: "condominio", aliases: ["Condomínio Terras de Santa Cruz"] },
  { nome: "Terras Nobres", tipo: "condominio", aliases: ["Residencial Terras Nobres"] },
  { nome: "Vale das Águas", tipo: "condominio", aliases: ["GSP Vale das Águas"] },
  { nome: "Villa Di Parma", tipo: "condominio", aliases: ["Condomínio Villa Di Parma","Residencial Villa Di Parma","Villa de Parma","Vila Di Parma"], address: "Rua Santa Maria, 236 — Vila Santa Terezinha", lat: -23.006132, lng: -46.829095 },
  { nome: "Villa Ravenna", tipo: "condominio", aliases: ["Condomínio Residencial Villa Ravenna","Villa Ravena","Ravenna"] },
  { nome: "Village das Palmeiras", tipo: "condominio", aliases: ["Condomínio Village das Palmeiras"] },
  { nome: "Villaggio Fosuzzi", tipo: "condominio" },
  { nome: "Villaggio Paradiso", tipo: "condominio", aliases: ["Condomínio Villagio Paradiso","Residencial Paradiso"], lat: -23.0577464, lng: -46.9054195 },
  { nome: "Villagio das Amoreiras", tipo: "condominio" },
  { nome: "Villagio Piu Verde", tipo: "condominio", aliases: ["Villagio Piu Verdi","Piu Verde"] },
  { nome: "Ville de Chamonix", tipo: "condominio", aliases: ["Ville Chamonix"] },
  { nome: "Ville de France", tipo: "condominio", aliases: ["Condomínio Ville de France","Ville de France Fechado"], lat: -22.9824823, lng: -46.8525293 },
  { nome: "Vista da Mata", tipo: "condominio", aliases: ["Condomínio Vista da Mata"] },
];
