window.ITATIBA_LOCAIS = [
  { nome: "Centro", tipo: "bairro", lat: -23.0056, lng: -46.8389 },
  { nome: "Parque São Francisco", tipo: "bairro", lat: -23.0027, lng: -46.8142 },
  { nome: "Bairro Tapera Grande", tipo: "bairro", aliases: ["Tapera Grande"], lat: -23.0483583, lng: -46.8775538 },
  { nome: "Jardim de Lucca", tipo: "bairro", aliases: ["Jardim de Luca"] },
  { nome: "Nova Itatiba", tipo: "bairro" },
  { nome: "Vila Santa Cruz", tipo: "bairro" },
  { nome: "Jardim Santa Cruz", tipo: "bairro" },
  { nome: "Jardim Alto de Santa Cruz", tipo: "bairro" },
  { nome: "Parque da Colina", tipo: "bairro" },
  { nome: "Princesa da Colina", tipo: "bairro" },
  { nome: "Recanto das Laranjeiras", tipo: "bairro" },
  { nome: "Jardim Nice", tipo: "bairro" },
  { nome: "Jardim Arizona", tipo: "bairro" },
  { nome: "Jardim México", tipo: "bairro" },
  { nome: "Vila Brasileira", tipo: "bairro" },
  { nome: "Vila Cruzeiro", tipo: "bairro" },
  { nome: "Bairro do Engenho", tipo: "bairro", aliases: ["Engenho"] },
  { nome: "Núcleo Residencial Doutor Luiz de Mattos Pimenta", tipo: "bairro" },
  { nome: "Capela do Barreiro", tipo: "bairro" },
  { nome: "Barreiro", tipo: "bairro" },
  { nome: "Vivendas do Engenho D'Água", tipo: "bairro" },
  { nome: "Bairro da Ponte", tipo: "bairro" },
  { nome: "Bairro da Posse", tipo: "bairro" },
  { nome: "Bairro das Brotas", tipo: "bairro" },
  { nome: "Bairro do Morro", tipo: "bairro" },
  { nome: "Bairro do Pinhal", tipo: "bairro" },
  { nome: "Bairro dos Baldos", tipo: "bairro" },
  { nome: "Bairro dos Leites", tipo: "bairro" },
  { nome: "Bairro dos Machados", tipo: "bairro" },
  { nome: "Bairro dos Pintos", tipo: "bairro" },
  { nome: "Bairro dos Pires", tipo: "bairro" },
  { nome: "Bairro Itapema", tipo: "bairro" },
  { nome: "Bairro Morro Azul", tipo: "bairro" },
  { nome: "Bairro Pedras de Ouro", tipo: "bairro" },
  { nome: "Bairro da Aparecidinha", tipo: "bairro" },
  { nome: "Alpes do Cruzeiro", tipo: "bairro" },
  { nome: "Bela Vista", tipo: "bairro" },
  { nome: "Cachoeiras do Imaratá", tipo: "bairro" },
  { nome: "Cidade Jardim", tipo: "bairro" },
  { nome: "Clube de Campo Fazenda", tipo: "bairro" },
  { nome: "Jardim Nossa Senhora das Graças", tipo: "bairro" },
  { nome: "Jardim Nossa Senhora de Fátima", tipo: "bairro" },
  { nome: "Jardim São Luiz", tipo: "bairro" },
  { nome: "Jardim São Luiz II", tipo: "bairro" },
  { nome: "Jardim Galetto", tipo: "bairro" },
  { nome: "Jardim Monte Verde", tipo: "bairro" },
  { nome: "Jardim Belém", tipo: "bairro" },
  { nome: "Jardim Coronel", tipo: "bairro" },
  { nome: "Jardim Belvedere", tipo: "bairro" },
  { nome: "Jardim Nova Itatiba", tipo: "bairro" },
  { nome: "Loteamento Residencial Vale das Águas", tipo: "bairro", aliases: ["Vale das Águas"] },
  { nome: "Núcleo Habitacional Pedro Costa", tipo: "bairro" },
  { nome: "Núcleo Habitacional Prefeito Erasmo Chrispim", tipo: "bairro" },
  { nome: "Núcleo Habitacional Roberto Panzarin", tipo: "bairro" },
  { nome: "Parque Luís Latorre", tipo: "bairro", aliases: ["Parque Luis Latorre"] },
  { nome: "Parque Ferraz Costa", tipo: "bairro" },
  { nome: "Parque Industrial San Francisco", tipo: "bairro" },
  { nome: "Real Parque Dom Pedro I", tipo: "bairro" },
  { nome: "Recreio Costa Verde", tipo: "bairro" },
  { nome: "Vila Prudente de Moraes", tipo: "bairro" },
  { nome: "Chácara San Martin I", tipo: "bairro" },
  { nome: "Chácara San Martin II", tipo: "bairro" },
  { nome: "Chácara Santa Cruz dos Pires", tipo: "bairro" },
  { nome: "Distrito Industrial Alfredo Relo", tipo: "bairro" },
  { nome: "Loteamento Aída Haddad Jafet", tipo: "bairro" },
  { nome: "Centro Empresarial Roque Faccina", tipo: "bairro" },
  { nome: "Encosta do Sol", tipo: "bairro" },
  { nome: "Morada dos Pássaros", tipo: "bairro" },
  { nome: "Jardim Santa Rosa", tipo: "bairro" },

  {
    nome: "Ville de France",
    tipo: "condominio",
    aliases: ["Condomínio Ville de France", "Ville de France Fechado"],
    lat: -22.9824823,
    lng: -46.8525293,
  },
  {
    nome: "Itatiba Country Club",
    tipo: "condominio",
    aliases: ["Condomínio Itatiba Country Club", "Country Club"],
    lat: -23.0221311,
    lng: -46.8147891,
  },
  {
    nome: "Beija-Flor",
    tipo: "condominio",
    aliases: ["Condomínio Residencial Beija-Flor", "Residencial Beija Flor", "Cond. Beija Flor"],
    lat: -23.0163221,
    lng: -46.8290591,
  },
  {
    nome: "Fazenda Dona Carolina",
    tipo: "condominio",
    aliases: ["Loteamento Fazenda Dona Carolina", "Dona Carolina"],
    lat: -22.939588,
    lng: -46.7010142,
  },
  {
    nome: "Villa Ravenna",
    tipo: "condominio",
    aliases: ["Condomínio Residencial Villa Ravenna", "Villa Ravena", "Ravenna"],
  },
  {
    nome: "Reserva Santa Rosa",
    tipo: "condominio",
    aliases: ["Condomínio Reserva Santa Rosa", "Reserva de Santa Rosa", "Residencial Fazenda Santa Rosa"],
  },
  { nome: "Bosque dos Pires", tipo: "condominio", aliases: ["Condomínio Bosque dos Pires"] },
  { nome: "Terras de San Marco", tipo: "condominio", aliases: ["San Marco"] },
  { nome: "Village das Palmeiras", tipo: "condominio", aliases: ["Condomínio Village das Palmeiras"] },
  { nome: "Villagio Piu Verde", tipo: "condominio", aliases: ["Villagio Piu Verdi", "Piu Verde"] },
  { nome: "Novo Engenho Place", tipo: "condominio", aliases: ["Condomínio Novo Engenho Place", "Engenho Place"] },
  { nome: "Ecologie Residencial", tipo: "condominio", aliases: ["Ecologie Residencial Itatiba", "Ecologie"] },
  { nome: "Portal San Giovanni", tipo: "condominio", aliases: ["Portal San Giovani", "San Giovanni"] },
  { nome: "Sete Lagos", tipo: "condominio", aliases: ["Condomínio 7 Lagos", "7 Lagos"] },
  { nome: "Terras da Fazenda", tipo: "condominio", aliases: ["Loteamento Terras da Fazenda"] },
  { nome: "Dolce Vita", tipo: "condominio", aliases: ["Loteamento Residencial Dolce Vita"] },
  { nome: "Itaembú", tipo: "condominio", aliases: ["Condomínio Itaembu", "Itaembu"] },
  { nome: "Reserva da Mata", tipo: "condominio", aliases: ["Condomínio Residencial Reserva da Mata"] },
  { nome: "Terras de Santa Cruz", tipo: "condominio", aliases: ["Condomínio Terras de Santa Cruz"] },
  { nome: "Vista da Mata", tipo: "condominio", aliases: ["Condomínio Vista da Mata"] },
  { nome: "Botanique", tipo: "condominio", aliases: ["Condomínio Botanique Itatiba"] },
  { nome: "Arts", tipo: "condominio", aliases: ["Condomínio Arts", "GSP Arts"] },
  { nome: "Villaggio Paradiso", tipo: "condominio", aliases: ["Condomínio Villagio Paradiso", "Residencial Paradiso"] },
  { nome: "Savoia Palace", tipo: "condominio", aliases: ["Savoia Palace Itatiba"] },
  { nome: "Jardim Botânico", tipo: "condominio", aliases: ["Loteamento Residencial Jardim Botânico"] },
  { nome: "Green Ville", tipo: "condominio", aliases: ["Residencial Green Ville"] },
  { nome: "Villa Di Parma", tipo: "condominio" },
  { nome: "San Paolo Residencial", tipo: "condominio", aliases: ["San Paolo"] },
  { nome: "Terras Nobres", tipo: "condominio", aliases: ["Residencial Terras Nobres"] },
  { nome: "Reserva Bellano", tipo: "condominio", aliases: ["Residencial Reserva Bellano"] },
  { nome: "Bella Morada", tipo: "condominio", aliases: ["Residencial Bella Morada"] },
  { nome: "Central Park", tipo: "condominio", aliases: ["Central Park I", "Central Park II"] },
  { nome: "Vale das Águas", tipo: "condominio", aliases: ["GSP Vale das Águas"] },
  { nome: "Portal de Itá", tipo: "condominio", aliases: ["Portal de Ita"] },
  { nome: "Ville de Chamonix", tipo: "condominio", aliases: ["Ville Chamonix"] },
  { nome: "Villagio das Amoreiras", tipo: "condominio" },
  { nome: "Quinta da Primavera", tipo: "condominio" },
  { nome: "Sonhare", tipo: "condominio" },
  { nome: "Exclusivitat", tipo: "condominio" },
  { nome: "San Diego", tipo: "condominio" },
  { nome: "Morada das Fontes", tipo: "bairro" },
  { nome: "Residencial Tescarollo", tipo: "condominio" },
  { nome: "Parque da Fazenda", tipo: "bairro" },
  { nome: "Parque São Gabriel", tipo: "bairro" },
];

window.ITATIBA_BAIRROS = window.ITATIBA_LOCAIS;
