// Lista de bairros, loteamentos e condomínios de Itatiba (SP).
// Fontes: base local + índice postal MBI (~166 localidades) + OpenStreetMap.
// Entradas sem lat/lng ainda entram na busca; o geocoder tenta resolver na hora.
window.ITATIBA_LOCAIS = [
  { nome: "Alpes do Cruzeiro", tipo: "bairro" },
  { nome: "Bairro da Aparecidinha", tipo: "bairro", aliases: ["da Aparecidinha"] },
  { nome: "Bairro da Ponte", tipo: "bairro", aliases: ["da Ponte"] },
  { nome: "Bairro da Posse", tipo: "bairro", aliases: ["da Posse"] },
  { nome: "Bairro das Brotas", tipo: "bairro", aliases: ["das Brotas"] },
  {
    nome: "Bairro do Engenho",
    tipo: "bairro",
    aliases: ["Engenho", "do Engenho", "Engenho Itatiba"],
    address: "Rua José de Oliveira — Bairro do Engenho",
    lat: -23.0213768,
    lng: -46.846043,
  },
  { nome: "Bairro do Morro", tipo: "bairro", aliases: ["do Morro"] },
  { nome: "Bairro do Pinhal", tipo: "bairro", aliases: ["do Pinhal"] },
  { nome: "Bairro dos Baldos", tipo: "bairro", aliases: ["dos Baldos"], lat: -22.9679908, lng: -46.9109734 },
  { nome: "Bairro dos Leites", tipo: "bairro", aliases: ["dos Leites"] },
  { nome: "Bairro dos Machados", tipo: "bairro", aliases: ["dos Machados"] },
  { nome: "Bairro dos Pintos", tipo: "bairro", aliases: ["dos Pintos"] },
  { nome: "Bairro dos Pires", tipo: "bairro", aliases: ["dos Pires"] },
  { nome: "Bairro Itapema", tipo: "bairro", aliases: ["Itapema"] },
  { nome: "Bairro Morro Azul", tipo: "bairro", aliases: ["Morro Azul"] },
  { nome: "Bairro Pedras de Ouro", tipo: "bairro", aliases: ["Pedras de Ouro"] },
  { nome: "Bairro Tapera Grande", tipo: "bairro", aliases: ["Tapera Grande"], lat: -23.0483583, lng: -46.8775538 },
  { nome: "Barreiro", tipo: "bairro", lat: -22.9407003, lng: -46.7240452 },
  { nome: "Bela Vista", tipo: "bairro" },
  { nome: "Cachoeiras do Imaratá", tipo: "bairro" },
  { nome: "Capela do Barreiro", tipo: "bairro", lat: -22.9407003, lng: -46.7240452 },
  { nome: "Centro", tipo: "bairro", lat: -23.0056, lng: -46.8389 },
  { nome: "Centro Empresarial Roque Faccina", tipo: "bairro" },
  { nome: "Chácara San Martin I", tipo: "bairro" },
  { nome: "Chácara San Martin II", tipo: "bairro" },
  { nome: "Chácara Santa Cruz dos Pires", tipo: "bairro" },
  { nome: "Chácaras Bredariol", tipo: "bairro" },
  { nome: "Cidade Jardim", tipo: "bairro", lat: -23.0128476, lng: -46.8274108 },
  { nome: "Clube de Campo Fazenda", tipo: "bairro" },
  { nome: "Cocais", tipo: "bairro" },
  { nome: "Distrito Industrial Alfredo Relo", tipo: "bairro" },
  { nome: "Encosta do Sol", tipo: "bairro" },
  { nome: "Fazenda Malabar", tipo: "bairro" },
  { nome: "Jardim Alto de Santa Cruz", tipo: "bairro" },
  { nome: "Jardim América", tipo: "bairro" },
  { nome: "Jardim Ana Maria", tipo: "bairro" },
  { nome: "Jardim Arizona", tipo: "bairro", lat: -23.0199526, lng: -46.8378857 },
  { nome: "Jardim Belém", tipo: "bairro", lat: -23.0177202, lng: -46.8389947 },
  { nome: "Jardim Belvedere", tipo: "bairro" },
  { nome: "Jardim Carlos Borella", tipo: "bairro" },
  { nome: "Jardim Coronel", tipo: "bairro" },
  { nome: "Jardim Coronel Peroba", tipo: "bairro" },
  { nome: "Jardim da Luz", tipo: "bairro", lat: -23.0214011, lng: -46.8428028 },
  { nome: "Jardim das Laranjeiras", tipo: "bairro" },
  { nome: "Jardim das Nações", tipo: "bairro", lat: -23.0071656, lng: -46.8673999 },
  { nome: "Jardim de Lucca", tipo: "bairro", aliases: ["Jardim de Luca"], lat: -23.0117724, lng: -46.8428958 },
  { nome: "Jardim Delforno", tipo: "bairro" },
  { nome: "Jardim do Leste", tipo: "bairro" },
  { nome: "Jardim dos Lagos", tipo: "bairro" },
  { nome: "Jardim Esplanada", tipo: "bairro" },
  { nome: "Jardim Ester", tipo: "bairro" },
  { nome: "Jardim Galetto", tipo: "bairro", lat: -23.0107836, lng: -46.8228636 },
  { nome: "Jardim Harmonia", tipo: "bairro" },
  { nome: "Jardim Ipê", tipo: "bairro" },
  { nome: "Jardim Leonor", tipo: "bairro", lat: -22.9657428, lng: -46.8182441 },
  { nome: "Jardim Lúcia", tipo: "bairro" },
  { nome: "Jardim Maria", tipo: "bairro" },
  { nome: "Jardim Mateus", tipo: "bairro", lat: -23.0083593, lng: -46.8356228 },
  { nome: "Jardim México", tipo: "bairro" },
  { nome: "Jardim Monte Verde", tipo: "bairro" },
  { nome: "Jardim Morumbi", tipo: "bairro" },
  { nome: "Jardim Nardin", tipo: "bairro" },
  { nome: "Jardim Nice", tipo: "bairro" },
  { nome: "Jardim Nossa Senhora das Graças", tipo: "bairro" },
  {
    nome: "Jardim Nossa Senhora de Fátima",
    tipo: "bairro",
    aliases: [
      "Nossa Senhora de Fátima",
      "Nossa Senhora de Fatima",
      "Bairro Nossa Senhora de Fátima",
      "Bairro Nossa Senhora de Fatima",
      "Jardim Nossa Senhora de Fatima",
    ],
    address: "Rua João Corradini — Jardim Nossa Senhora de Fátima",
    lat: -23.0096313,
    lng: -46.8465374,
  },
  { nome: "Jardim Nova América", tipo: "bairro" },
  { nome: "Jardim Nova Esperança", tipo: "bairro", lat: -22.9660936, lng: -46.9135595 },
  { nome: "Jardim Nova Itatiba", tipo: "bairro", lat: -22.9660936, lng: -46.9135595 },
  { nome: "Jardim Novo Horizonte", tipo: "bairro" },
  { nome: "Jardim Palladino", tipo: "bairro" },
  { nome: "Jardim Salessi", tipo: "bairro" },
  { nome: "Jardim Santa Cruz", tipo: "bairro" },
  { nome: "Jardim Santa Filomena", tipo: "bairro" },
  { nome: "Jardim Santa Rosa", tipo: "bairro", lat: -23.0262918, lng: -46.8413125 },
  { nome: "Jardim Santo Antônio", tipo: "bairro" },
  { nome: "Jardim São João", tipo: "bairro" },
  { nome: "Jardim São José", tipo: "bairro", lat: -23.0077372, lng: -46.8373019 },
  { nome: "Jardim São Luiz", tipo: "bairro" },
  { nome: "Jardim São Luiz II", tipo: "bairro" },
  { nome: "Jardim São Marcos", tipo: "bairro" },
  { nome: "Jardim Tereza", tipo: "bairro", lat: -23.0109234, lng: -46.8332047 },
  { nome: "Jardim Verona", tipo: "bairro" },
  { nome: "Jardim Virgínia", tipo: "bairro" },
  { nome: "Loteamento Aída Haddad Jafet", tipo: "bairro", lat: -23.012479, lng: -46.8646634 },
  { nome: "Loteamento Caminhos do Sol", tipo: "bairro" },
  { nome: "Loteamento Fernando Momentel", tipo: "bairro" },
  { nome: "Loteamento Itatiba Country Club", tipo: "bairro" },
  { nome: "Loteamento Itatiba Park", tipo: "bairro", lat: -23.0301784, lng: -46.8513301 },
  { nome: "Loteamento Padovani", tipo: "bairro" },
  { nome: "Loteamento Parque da Colina II", tipo: "bairro", lat: -23.0131598, lng: -46.8240803 },
  { nome: "Loteamento Parque Empresarial Adelelmo Corradini", tipo: "bairro" },
  { nome: "Loteamento Rei de Ouro", tipo: "bairro" },
  { nome: "Loteamento Residencial Central Park I", tipo: "bairro", lat: -23.0131598, lng: -46.8240803 },
  { nome: "Loteamento Residencial Central Park II", tipo: "bairro" },
  { nome: "Loteamento Residencial Terra Nova", tipo: "bairro" },
  { nome: "Loteamento Residencial Vale das Águas", tipo: "bairro", aliases: ["Vale das Águas"] },
  { nome: "Loteamento Santo Antônio", tipo: "bairro" },
  { nome: "Loteamento Vila Real", tipo: "bairro" },
  { nome: "Mato Dentro", tipo: "bairro" },
  { nome: "Mombuca", tipo: "bairro" },
  { nome: "Morada das Fontes", tipo: "bairro" },
  { nome: "Morada dos Pássaros", tipo: "bairro", lat: -23.0184942, lng: -46.8306083 },
  { nome: "Nova Itatiba", tipo: "bairro", lat: -23.0978173, lng: -46.8412392 },
  { nome: "Novo Cruzeiro", tipo: "bairro", aliases: ["Bairro Novo Cruzeiro","Novo Cuzeiro","Bairro Novo Cuzeiro"], address: "Rua Nagib Curi — Novo Cruzeiro", lat: -22.99726, lng: -46.85465 },
  { nome: "Núcleo Habitacional Pedro Costa", tipo: "bairro" },
  { nome: "Núcleo Habitacional Prefeito Erasmo Chrispim", tipo: "bairro" },
  { nome: "Núcleo Habitacional Roberto Panzarin", tipo: "bairro" },
  { nome: "Núcleo Residencial Abramo Delforno", tipo: "bairro" },
  { nome: "Núcleo Residencial Afonso Zupardo", tipo: "bairro" },
  { nome: "Núcleo Residencial Doutor Luiz de Mattos Pimenta", tipo: "bairro", lat: -23.021734, lng: -46.8501954 },
  { nome: "Núcleo Residencial João Corradini", tipo: "bairro" },
  { nome: "Núcleo Residencial Pedro Fumachi", tipo: "bairro" },
  { nome: "Núcleo Residencial Porto Seguro", tipo: "bairro", lat: -23.0289186, lng: -46.8529801 },
  { nome: "Núcleo Residencial Vale Verde", tipo: "bairro" },
  { nome: "Paraíso das Aves", tipo: "bairro" },
  { nome: "Parque da Colina", tipo: "bairro", lat: -23.0140447, lng: -46.8173854 },
  { nome: "Parque da Fazenda", tipo: "bairro", lat: -23.033701, lng: -46.8410556 },
  { nome: "Parque das Laranjeiras", tipo: "bairro" },
  { nome: "Parque Ferraz Costa", tipo: "bairro", lat: -22.9995115, lng: -46.8335248 },
  { nome: "Parque Industrial San Francisco", tipo: "bairro" },
  { nome: "Parque Luís Latorre", tipo: "bairro", aliases: ["Parque Luis Latorre"], lat: -23.0316212, lng: -46.8391448 },
  { nome: "Parque Nova Xampirra", tipo: "bairro" },
  { nome: "Parque São Francisco", tipo: "bairro", lat: -23.0027, lng: -46.8142 },
  { nome: "Parque São Gabriel", tipo: "bairro" },
  { nome: "Parque São Vicente", tipo: "bairro" },
  { nome: "Parque Tescarollo", tipo: "bairro" },
  { nome: "Pomar São Jorge", tipo: "bairro" },
  { nome: "Ponte Nova", tipo: "bairro" },
  { nome: "Portal da Colina", tipo: "bairro" },
  { nome: "Princesa da Colina", tipo: "bairro" },
  { nome: "Real Parque Dom Pedro I", tipo: "bairro" },
  { nome: "Recanto Beira Rio", tipo: "bairro" },
  { nome: "Recanto da Paz", tipo: "bairro" },
  { nome: "Recanto das Estrelas", tipo: "bairro" },
  { nome: "Recanto das Laranjeiras", tipo: "bairro" },
  { nome: "Recanto do Parque", tipo: "bairro" },
  { nome: "Recanto dos Pássaros", tipo: "bairro" },
  { nome: "Recanto Princesa da Colina", tipo: "bairro" },
  { nome: "Recreio Costa Verde", tipo: "bairro" },
  { nome: "Residencial Fazenda Serrinha", tipo: "bairro", lat: -23.0179425, lng: -46.8254953 },
  { nome: "Residencial Flamboyant", tipo: "bairro" },
  { nome: "Residencial Grêmio", tipo: "bairro" },
  { nome: "Residencial Moenda", tipo: "bairro" },
  { nome: "Santa Cruz", tipo: "bairro", lat: -22.997394, lng: -46.8351906 },
  { nome: "Sítio da Moenda", tipo: "bairro" },
  { nome: "Summertime Barreiro", tipo: "bairro" },
  { nome: "Terras de São Sebastião", tipo: "bairro" },
  { nome: "Terras de Savion", tipo: "bairro" },
  { nome: "Vila Bela Vista", tipo: "bairro" },
  { nome: "Vila Brasileira", tipo: "bairro", lat: -23.0052691, lng: -46.8488421 },
  { nome: "Vila Capelletto", tipo: "bairro" },
  { nome: "Vila Cassaro", tipo: "bairro" },
  { nome: "Vila Centenário", tipo: "bairro" },
  { nome: "Vila Cremonesi", tipo: "bairro" },
  { nome: "Vila Cristo Redentor", tipo: "bairro" },
  { nome: "Vila Cruzeiro", tipo: "bairro", aliases: ["Cruzeiro","Cuzeiro","Bairro Cruzeiro","Bairro Cuzeiro","Praça Cruzeiro"], address: "Praça Cruzeiro — Vila Cruzeiro", lat: -23.0039859, lng: -46.8467996 },
  { nome: "Vila Fassina", tipo: "bairro" },
  { nome: "Vila Mutton", tipo: "bairro", lat: -23.0019522, lng: -46.8353315 },
  { nome: "Vila Penteado", tipo: "bairro" },
  { nome: "Vila Prudente de Moraes", tipo: "bairro" },
  { nome: "Vila Rita", tipo: "bairro" },
  { nome: "Vila Santa Clara", tipo: "bairro" },
  { nome: "Vila Santa Cruz", tipo: "bairro" },
  { nome: "Vila Santa Luzia", tipo: "bairro", lat: -23.012325, lng: -46.8457549 },
  { nome: "Vila Santa Terezinha", tipo: "bairro", lat: -23.0079944, lng: -46.829861 },
  { nome: "Vila São Caetano", tipo: "bairro" },
  { nome: "Village de Piemonte", tipo: "bairro" },
  { nome: "Village do Sol", tipo: "bairro" },
  { nome: "Vivendas do Engenho D'Água", tipo: "bairro" },
  { nome: "Arts", tipo: "condominio", aliases: ["Condomínio Arts","GSP Arts"] },
  { nome: "Beija-Flor", tipo: "condominio", aliases: ["Condomínio Residencial Beija-Flor","Residencial Beija Flor","Cond. Beija Flor"], lat: -23.0163221, lng: -46.8290591 },
  { nome: "Bella Morada", tipo: "condominio", aliases: ["Residencial Bella Morada"] },
  { nome: "Bosque dos Pires", tipo: "condominio", aliases: ["Condomínio Bosque dos Pires"] },
  { nome: "Botanique", tipo: "condominio", aliases: ["Condomínio Botanique Itatiba"] },
  { nome: "Central Park", tipo: "condominio", aliases: ["Central Park I","Central Park II"], lat: -23.0131598, lng: -46.8240803 },
  { nome: "Dolce Vita", tipo: "condominio", aliases: ["Loteamento Residencial Dolce Vita"] },
  { nome: "Ecologie Residencial", tipo: "condominio", aliases: ["Ecologie Residencial Itatiba","Ecologie"] },
  { nome: "Exclusivitat", tipo: "condominio" },
  { nome: "Fazenda Dona Carolina", tipo: "condominio", aliases: ["Loteamento Fazenda Dona Carolina","Dona Carolina"], lat: -22.939588, lng: -46.7010142 },
  { nome: "Giardino D' Itália", tipo: "condominio" },
  { nome: "Green Ville", tipo: "condominio", aliases: ["Residencial Green Ville"] },
  { nome: "Itaembú", tipo: "condominio", aliases: ["Condomínio Itaembu","Itaembu"] },
  { nome: "Itatiba Country Club", tipo: "condominio", aliases: ["Condomínio Itatiba Country Club","Country Club"], lat: -23.0221311, lng: -46.8147891 },
  { nome: "Jardim Botânico", tipo: "condominio", aliases: ["Loteamento Residencial Jardim Botânico"] },
  {
    nome: "Jardim das Paineiras",
    tipo: "condominio",
    aliases: [
      "Jardim Paineiras",
      "Paineiras",
      "Condomínio Jardim das Paineiras",
      "Condomínio Paineiras",
      "Loteamento Jardim das Paineiras",
      "Residencial Jardim das Paineiras",
    ],
    address: "Avenida Guido Monte — Loteamento Jardim das Paineiras",
    lat: -22.932409,
    lng: -46.81497,
  },
  { nome: "Novo Engenho Place", tipo: "condominio", aliases: ["Condomínio Novo Engenho Place","Engenho Place"] },
  { nome: "Portal de Itá", tipo: "condominio", aliases: ["Portal de Ita"], lat: -23.0174075, lng: -46.8309685 },
  { nome: "Portal San Giovanni", tipo: "condominio", aliases: ["Portal San Giovani","San Giovanni"] },
  {
    nome: "Privilege",
    tipo: "condominio",
    aliases: [
      "Condomínio Privilege",
      "Condominio Privilege",
      "Privilege Residencial",
      "Privilege Residencial Clube",
      "Residencial Privilege",
      "Residencial Privilége",
      "Privilége",
      "Privilége Residencial Clube",
      "Privilege Itatiba",
    ],
    address: "Rua Santo Antônio, 1750 — Jardim México, 13253-400",
    lat: -22.9991045,
    lng: -46.8174569,
  },
  { nome: "Quinta da Primavera", tipo: "condominio" },
  { nome: "Reserva Bellano", tipo: "condominio", aliases: ["Residencial Reserva Bellano"] },
  { nome: "Reserva da Mata", tipo: "condominio", aliases: ["Condomínio Residencial Reserva da Mata"] },
  { nome: "Reserva Santa Rosa", tipo: "condominio", aliases: ["Condomínio Reserva Santa Rosa","Reserva de Santa Rosa","Residencial Fazenda Santa Rosa"] },
  { nome: "Residencial Tescarollo", tipo: "condominio" },
  { nome: "San Diego", tipo: "condominio" },
  { nome: "San Paolo Residencial", tipo: "condominio", aliases: ["San Paolo"], lat: -23.0153039, lng: -46.8306789 },
  { nome: "Savoia Palace", tipo: "condominio", aliases: ["Savoia Palace Itatiba"] },
  { nome: "Sete Lagos", tipo: "condominio", aliases: ["Condomínio 7 Lagos","7 Lagos"] },
  { nome: "Sonhare", tipo: "condominio" },
  { nome: "Terras da Fazenda", tipo: "condominio", aliases: ["Loteamento Terras da Fazenda"] },
  { nome: "Terras de San Marco", tipo: "condominio", aliases: ["San Marco"] },
  { nome: "Terras de Santa Cruz", tipo: "condominio", aliases: ["Condomínio Terras de Santa Cruz"] },
  { nome: "Terras Nobres", tipo: "condominio", aliases: ["Residencial Terras Nobres"] },
  { nome: "Vale das Águas", tipo: "condominio", aliases: ["GSP Vale das Águas"] },
  { nome: "Villa Di Parma", tipo: "condominio", aliases: ["Condomínio Villa Di Parma","Residencial Villa Di Parma","Villa de Parma","Vila Di Parma"], address: "Rua Santa Maria, 236 — Vila Santa Terezinha", lat: -23.006132, lng: -46.829095 },
  { nome: "Villa Ravenna", tipo: "condominio", aliases: ["Condomínio Residencial Villa Ravenna","Villa Ravena","Ravenna"] },
  { nome: "Village das Palmeiras", tipo: "condominio", aliases: ["Condomínio Village das Palmeiras"] },
  { nome: "Villaggio Fosuzzi", tipo: "condominio" },
  { nome: "Villaggio Paradiso", tipo: "condominio", aliases: ["Condomínio Villagio Paradiso","Residencial Paradiso"], lat: -23.0577464, lng: -46.9054195 },
  { nome: "Villagio das Amoreiras", tipo: "condominio" },
  { nome: "Villagio Piu Verde", tipo: "condominio", aliases: ["Villagio Piu Verdi","Piu Verde"] },
  { nome: "Ville de Chamonix", tipo: "condominio", aliases: ["Ville Chamonix"] },
  { nome: "Ville de France", tipo: "condominio", aliases: ["Condomínio Ville de France","Ville de France Fechado"], lat: -22.9824823, lng: -46.8525293 },
  { nome: "Vista da Mata", tipo: "condominio", aliases: ["Condomínio Vista da Mata"] },
];
